---
name: "Kodi Sync Queue"
guid: "771e19d6-5385-4caf-b35c-28a0e865cf63"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-kodisyncqueue.png"
version: 11
targetAbi: "10.9.1.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Sync all media changes with Kodi clients"
description: "This plugin will track all media changes while Kodi clients are offline to decrease sync times."
category: "General"
artifacts:
  - "Jellyfin.Plugin.KodiSyncQueue.dll"
  - "LiteDB.dll"
changelog: |-
  - Downgrade LiteDB to 5.0.15 (#85) (#90) @crobibero
