---
name: "Kodi Sync Queue"
guid: "771e19d6-5385-4caf-b35c-28a0e865cf63"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-kodisyncqueue.png"
version: 10
targetAbi: "10.9.1.0"
framework: "net8.0"
owner: "jellyfin"
overview: "Sync all media changes with Kodi clients"
description: "This plugin will track all media changes while Kodi clients are offline to decrease sync times."
category: "General"
artifacts:
  - "Jellyfin.Plugin.KodiSyncQueue.dll"
  - "LiteDB.dll"
changelog: |-
  - 10.9 (#82) @crobibero

  ### Major bug fixes ###
  - Downgrade LiteDB to 5.0.15 (#85) @oddstr13

  ### New features and improvements ###
  - Implement IDisposable (#75) @crobibero

  ### Bug Fixes ###
  - Downgrade LiteDB to 5.0.15 (#85) @oddstr13

  ### Documentation updates ###
  - Fix openapi generation issues (#81) @crobibero

  ### Dependency updates ###
  - chore(deps): update dependency litedb to v5.0.19 (#78) @renovate
